// V3 Classroom Types — clean break from V2

/** Phase of the classroom session */
export type ClassroomPhase =
  | "idle"
  | "generating"
  | "teaching"
  | "student_turn"
  | "evaluating"
  | "reviewing"
  | "complete";

/** How the student should answer */
export type ExpectedAnswerType = "drawing" | "number" | "expression";

/** A tldraw-compatible shape definition for board rendering */
export type BoardShape = {
  shapeId: string; // must start with "teacher-"
  type: "geo" | "arrow" | "text";
  x: number;
  y: number;
  props: Record<string, unknown>;
  isLocked: true;
};

/** A single problem within a lesson */
export type LessonProblem = {
  problemId: string;
  problemText: string;
  boardShapes: BoardShape[];
  spokenPrompt: string;
  expectedAnswerType: ExpectedAnswerType;
  hints: string[];
};

/** A full lesson plan generated by AI */
export type LessonPlan = {
  lessonId: string;
  topic: string;
  gradeLevel: number;
  problems: LessonProblem[];
};

/** Events that occur during a classroom session */
export type SessionEvent =
  | { type: "lesson.started"; lessonId: string }
  | { type: "problem.presented"; problemId: string }
  | { type: "student.answered"; problemId: string; answer: unknown }
  | { type: "problem.evaluated"; problemId: string; correct: boolean }
  | { type: "hint.given"; problemId: string; hintIndex: number }
  | { type: "lesson.ended"; lessonId: string; reason: string };
